<!DOCTYPE html>
<html lang="ar">
<head>
  <meta charset="UTF-8">
  <title>موقعي الشخصي</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <h1>مرحباً بكم في موقعي!</h1>
  <p>هذا مثال بسيط لموقع HTML يوضح الترحيب بالنّاس.</p>
</body>
</html>